export type SkillKind = "business" | "ui";

export interface SkillMeta {
  kind: SkillKind;
  objectives: string[];
  requiresCanvas: boolean;
  canvasRoute?: string;
  inlineComponents: boolean;
}

/** Metadados de apresentação — separado das business actions. */
export const SKILL_META: Record<string, SkillMeta> = {
  "dashboard.show": {
    kind: "business",
    objectives: ["como está o negócio", "visão geral", "painel", "resumo"],
    requiresCanvas: true,
    canvasRoute: "/dashboard",
    inlineComponents: false,
  },
  "crm.leads.table": {
    kind: "business",
    objectives: ["ver leads", "meus leads", "listar leads"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "crm.clients.table": {
    kind: "business",
    objectives: ["ver clientes", "relacionamento", "base de clientes"],
    requiresCanvas: false,
    canvasRoute: "/clientes",
    inlineComponents: true,
  },
  "crm.clients.list": {
    kind: "business",
    objectives: ["lista de clientes"],
    requiresCanvas: false,
    canvasRoute: "/clientes",
    inlineComponents: true,
  },
  "lead.prospect": {
    kind: "business",
    objectives: ["prospectar leads", "buscar no mapa", "modo paleteiro"],
    requiresCanvas: false,
    canvasRoute: "/busca",
    inlineComponents: true,
  },
  "crm.leads.search": {
    kind: "business",
    objectives: ["buscar leads", "prospectar"],
    requiresCanvas: false,
    canvasRoute: "/busca",
    inlineComponents: true,
  },
  "crm.lead.find": {
    kind: "business",
    objectives: ["encontrar lead", "editar lead", "cadastrar cliente"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "campaigns.create": {
    kind: "business",
    objectives: ["criar campanha", "nova campanha", "disparar mensagens", "vender"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "campaigns.list": {
    kind: "business",
    objectives: ["ver campanhas", "campanhas ativas"],
    requiresCanvas: false,
    canvasRoute: "/campanhas",
    inlineComponents: true,
  },
  "messages.inbox": {
    kind: "business",
    objectives: ["responder cliente", "conversas", "mensagens", "atendimento"],
    requiresCanvas: false,
    inlineComponents: true,
    canvasRoute: "/mensagens",
  },
  "order.assisted": {
    kind: "business",
    objectives: ["fazer pedido", "tirar pedido", "pedido para"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "flow.builder": {
    kind: "ui",
    objectives: ["editor de fluxos", "configuração avançada"],
    requiresCanvas: true,
    canvasRoute: "/fluxos",
    inlineComponents: false,
  },
  "creative.generate": {
    kind: "business",
    objectives: ["criar criativo", "gerar imagem", "criativos ia"],
    requiresCanvas: true,
    canvasRoute: "/criativos",
    inlineComponents: false,
  },
  "video.create": {
    kind: "business",
    objectives: ["criar vídeo", "video studio"],
    requiresCanvas: true,
    canvasRoute: "/video-studio",
    inlineComponents: false,
  },
  "gallery.open": {
    kind: "business",
    objectives: ["abrir galeria", "minhas imagens"],
    requiresCanvas: false,
    canvasRoute: "/galeria",
    inlineComponents: true,
  },
  "agent.configure": {
    kind: "business",
    objectives: ["configurar agente", "treinar agente"],
    requiresCanvas: true,
    canvasRoute: "/agente",
    inlineComponents: false,
  },
  "workspace.overview": {
    kind: "business",
    objectives: ["status do agente", "prontidão"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "dashboard.overview": {
    kind: "business",
    objectives: ["resumo rápido", "kpis"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "catalog.products": {
    kind: "business",
    objectives: ["ver produtos", "catálogo"],
    requiresCanvas: false,
    canvasRoute: "/produtos",
    inlineComponents: true,
  },
  "catalog.products.table": {
    kind: "business",
    objectives: ["ver estoque", "tabela de produtos"],
    requiresCanvas: false,
    canvasRoute: "/produtos",
    inlineComponents: true,
  },
  "catalog.products.create": {
    kind: "business",
    objectives: ["criar produto", "cadastrar produto", "novo produto"],
    requiresCanvas: false,
    canvasRoute: "/produtos",
    inlineComponents: true,
  },
  "catalog.orders": {
    kind: "business",
    objectives: ["ver pedidos", "vendas", "ordens"],
    requiresCanvas: false,
    canvasRoute: "/pedidos",
    inlineComponents: true,
  },
  "skills.list": {
    kind: "business",
    objectives: ["ver habilidades"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "skills.train": {
    kind: "business",
    objectives: ["ensinar agente", "nova habilidade"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "nav.help": {
    kind: "ui",
    objectives: ["ajuda", "o que posso fazer"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "instagram.post.create": {
    kind: "business",
    objectives: ["criar post instagram", "gerar legenda", "publicar no insta"],
    requiresCanvas: false,
    canvasRoute: "/instagram",
    inlineComponents: true,
  },
  "instagram.post.confirm": {
    kind: "business",
    objectives: ["confirmar publicação", "agendar post"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "instagram.analyze": {
    kind: "business",
    objectives: ["analisar instagram", "métricas", "performance"],
    requiresCanvas: false,
    canvasRoute: "/instagram",
    inlineComponents: true,
  },
  "instagram.messages": {
    kind: "business",
    objectives: ["dms instagram", "mensagens direct"],
    requiresCanvas: false,
    canvasRoute: "/instagram",
    inlineComponents: true,
  },
  "facebook.open": {
    kind: "business",
    objectives: ["abrir facebook", "página facebook"],
    requiresCanvas: false,
    canvasRoute: "/facebook",
    inlineComponents: true,
  },
  "facebook.post.create": {
    kind: "business",
    objectives: ["criar post facebook", "publicar no fb"],
    requiresCanvas: false,
    canvasRoute: "/facebook",
    inlineComponents: true,
  },
  "facebook.post.confirm": {
    kind: "business",
    objectives: ["confirmar publicação facebook"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "facebook.analyze": {
    kind: "business",
    objectives: ["analisar facebook", "métricas fb"],
    requiresCanvas: false,
    canvasRoute: "/facebook",
    inlineComponents: true,
  },
  "automation.open": {
    kind: "business",
    objectives: ["ver automações", "fluxos whatsapp"],
    requiresCanvas: false,
    canvasRoute: "/fluxos",
    inlineComponents: true,
  },
  "automation.create": {
    kind: "business",
    objectives: ["criar fluxo pedido", "automação whatsapp", "comportamento reativo"],
    requiresCanvas: false,
    canvasRoute: "/fluxos",
    inlineComponents: true,
  },
  "automation.confirm": {
    kind: "business",
    objectives: ["ativar fluxo", "salvar automação"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "affiliate.open": {
    kind: "business",
    objectives: ["abrir afiliados", "programa de parceiros"],
    requiresCanvas: false,
    canvasRoute: "/afiliados",
    inlineComponents: true,
  },
  "affiliate.create": {
    kind: "business",
    objectives: ["cadastrar afiliado", "novo parceiro"],
    requiresCanvas: false,
    canvasRoute: "/afiliados",
    inlineComponents: true,
  },
  "affiliate.create.confirm": {
    kind: "business",
    objectives: ["confirmar cadastro afiliado"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "affiliate.config": {
    kind: "business",
    objectives: ["configurar programa afiliados", "comissão padrão"],
    requiresCanvas: false,
    canvasRoute: "/afiliados",
    inlineComponents: true,
  },
  "affiliate.config.confirm": {
    kind: "business",
    objectives: ["salvar config afiliados"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "affiliate.analyze": {
    kind: "business",
    objectives: ["métricas afiliados", "analisar parceiros"],
    requiresCanvas: false,
    canvasRoute: "/afiliados",
    inlineComponents: true,
  },
  "affiliate.approve": {
    kind: "business",
    objectives: ["aprovar comissão", "aprovar afiliado"],
    requiresCanvas: false,
    canvasRoute: "/afiliados",
    inlineComponents: true,
  },
  "affiliate.payouts": {
    kind: "business",
    objectives: ["saques afiliados", "pagar parceiro"],
    requiresCanvas: false,
    canvasRoute: "/afiliados",
    inlineComponents: true,
  },
  "affiliate.payout.confirm": {
    kind: "business",
    objectives: ["confirmar saque afiliado"],
    requiresCanvas: false,
    inlineComponents: true,
  },
  "affiliate.materials": {
    kind: "business",
    objectives: ["materiais afiliados"],
    requiresCanvas: false,
    canvasRoute: "/afiliados",
    inlineComponents: true,
  },
};

export function getSkillMeta(skillId: string): SkillMeta | null {
  return SKILL_META[skillId] || null;
}