import type { SkillDefinition, SquadDefinition } from "./types";

export const SKILLS: Record<string, SkillDefinition> = {
  "workspace.overview": {
    id: "workspace.overview",
    name: "Ver prontidão do agente",
    description: "Mostra score de prontidão e checklist do agente WhatsApp.",
    squad: "workspace",
    intents: ["como está meu agente", "prontidão", "readiness", "status do agente", "agente configurado"],
    permissions: ["agent.read"],
    ui: ["readiness_card", "checklist"],
  },
  "workspace.navigate": {
    id: "workspace.navigate",
    name: "Configurar agente",
    description: "Navega para a página de configuração do agente IA.",
    squad: "workspace",
    intents: ["configurar agente", "treinar agente", "editar agente", "perfil do agente"],
    permissions: ["agent.write"],
    ui: ["nav_suggestions"],
  },
  "crm.leads.list": {
    id: "crm.leads.list",
    name: "Listar leads",
    description: "Mostra resumo de leads e navega para a lista.",
    squad: "crm",
    intents: ["meus leads", "listar leads", "ver leads", "quantos leads"],
    permissions: ["leads.read"],
    ui: ["kpi_row", "nav_suggestions"],
  },
  "crm.leads.search": {
    id: "crm.leads.search",
    name: "Buscar leads",
    description: "Alias para busca no mapa (modo paleteiro).",
    squad: "crm",
    intents: ["buscar leads no mapa"],
    permissions: ["leads.read"],
    ui: ["form", "prospect_stats"],
  },
  "lead.prospect": {
    id: "lead.prospect",
    name: "Prospectar no mapa",
    description: "Busca Google Maps com modo paleteiro — arrastar, capturar, radar.",
    squad: "crm",
    intents: ["prospectar", "buscar no mapa", "paleteiro", "panfleteiro", "google maps", "encontrar empresas", "prospectar leads"],
    permissions: ["leads.read", "leads.write"],
    ui: ["form", "prospect_stats"],
  },
  "crm.leads.table": {
    id: "crm.leads.table",
    name: "Tabela de leads recentes",
    description: "Mostra tabela com os leads mais recentes.",
    squad: "crm",
    intents: ["tabela de leads", "últimos leads", "leads recentes"],
    permissions: ["leads.read"],
    ui: ["table", "kpi_row"],
  },
  "crm.lead.find": {
    id: "crm.lead.find",
    name: "Buscar lead por nome",
    description: "Formulário de busca e tabela de resultados.",
    squad: "crm",
    intents: ["encontrar lead", "lead chamado", "procurar lead", "editar lead"],
    permissions: ["leads.read"],
    ui: ["form", "table"],
  },
  "crm.clients.table": {
    id: "crm.clients.table",
    name: "Ver clientes",
    description: "Lista clientes convertidos e relacionamento ativo.",
    squad: "crm",
    intents: ["clientes", "ver clientes", "meus clientes", "base de clientes"],
    permissions: ["clients.read"],
    ui: ["clients_stats", "kpi_row", "table"],
  },
  "crm.clients.list": {
    id: "crm.clients.list",
    name: "Lista de clientes",
    description: "Tabela de clientes com filtros.",
    squad: "crm",
    intents: ["lista de clientes", "tabela clientes"],
    permissions: ["clients.read"],
    ui: ["clients_stats", "table"],
  },
  "crm.lead.detail": {
    id: "crm.lead.detail",
    name: "Detalhe do lead",
    description: "Card com dados do lead selecionado.",
    squad: "crm",
    intents: [],
    permissions: ["leads.read"],
    ui: ["lead_card", "button"],
  },
  "messages.inbox": {
    id: "messages.inbox",
    name: "Conversas recentes",
    description: "Tabela com últimas conversas WhatsApp.",
    squad: "messages",
    intents: ["mensagens", "conversas", "inbox", "whatsapp conversas", "atendimento"],
    permissions: ["messages.read"],
    ui: ["table", "kpi_row"],
  },
  "catalog.products.table": {
    id: "catalog.products.table",
    name: "Tabela de produtos",
    description: "Lista produtos com estoque.",
    squad: "catalog",
    intents: ["lista de produtos", "tabela produtos", "ver estoque detalhado"],
    permissions: ["catalog.read"],
    ui: ["products_stats", "table"],
  },
  "campaigns.list": {
    id: "campaigns.list",
    name: "Ver campanhas",
    description: "Mostra campanhas ativas e totais.",
    squad: "campaigns",
    intents: ["campanhas", "minhas campanhas", "campanhas ativas"],
    permissions: ["campaigns.read"],
    ui: ["campaigns_stats", "kpi_row", "nav_suggestions"],
  },
  "campaigns.create": {
    id: "campaigns.create",
    name: "Criar campanha com IA",
    description: "Abre o wizard de criação de campanha via squad de IA.",
    squad: "campaigns",
    intents: ["criar campanha", "nova campanha", "campanha com ia", "disparar mensagens"],
    permissions: ["campaigns.write"],
    ui: ["confirmation"],
  },
  "skills.list": {
    id: "skills.list",
    name: "Ver habilidades",
    description: "Lista habilidades (brand skills) do agente.",
    squad: "skills",
    intents: ["habilidades", "skills", "o que o agente sabe"],
    permissions: ["skills.read"],
    ui: ["skill_list", "nav_suggestions"],
  },
  "skills.train": {
    id: "skills.train",
    name: "Ensinar nova habilidade",
    description: "Abre o wizard de treinamento de habilidade.",
    squad: "skills",
    intents: ["ensinar agente", "nova habilidade", "treinar skill", "criar habilidade"],
    permissions: ["skills.write"],
    ui: ["confirmation"],
  },
  "catalog.products": {
    id: "catalog.products",
    name: "Ver produtos",
    description: "Mostra resumo do catálogo e estoque.",
    squad: "catalog",
    intents: ["produtos", "catálogo", "estoque", "inventário"],
    permissions: ["catalog.read"],
    ui: ["products_stats", "kpi_row", "nav_suggestions"],
  },
  "catalog.products.create": {
    id: "catalog.products.create",
    name: "Criar produto",
    description: "Fluxo conversacional para cadastrar produto com IA.",
    squad: "catalog",
    intents: ["criar produto", "novo produto", "cadastrar produto", "adicionar produto", "lançar produto"],
    permissions: ["catalog.write"],
    ui: ["form", "confirmation", "text"],
  },
  "catalog.orders": {
    id: "catalog.orders",
    name: "Ver pedidos",
    description: "Mostra resumo de pedidos da loja.",
    squad: "catalog",
    intents: ["pedidos", "vendas", "ordens"],
    permissions: ["catalog.read"],
    ui: ["orders_stats", "kpi_row", "table"],
  },
  "nav.help": {
    id: "nav.help",
    name: "Ajuda e navegação",
    description: "Sugere rotas e ações disponíveis no painel.",
    squad: "nav",
    intents: ["ajuda", "o que posso fazer", "menu", "navegar", "ir para"],
    permissions: [],
    ui: ["nav_suggestions"],
  },
  "dashboard.overview": {
    id: "dashboard.overview",
    name: "Visão geral",
    description: "KPIs principais do negócio (inline).",
    squad: "dashboard",
    intents: ["resumo rápido", "kpis", "números do negócio"],
    permissions: [],
    ui: ["kpi_row", "nav_suggestions"],
  },
  "dashboard.show": {
    id: "dashboard.show",
    name: "Painel completo",
    description: "Abre o dashboard no canvas lateral.",
    squad: "dashboard",
    intents: ["painel", "dashboard", "visão geral", "como está o negócio", "mostrar painel"],
    permissions: [],
    ui: [],
  },
  "order.assisted": {
    id: "order.assisted",
    name: "Pedido assistido",
    description: "Fluxo conversacional para montar um pedido.",
    squad: "catalog",
    intents: ["fazer pedido", "tirar pedido", "pedido para", "preciso fazer um pedido"],
    permissions: ["catalog.write"],
    ui: ["form", "table", "confirmation"],
  },
  "flow.builder": {
    id: "flow.builder",
    name: "Editor de fluxos",
    description: "Abre o flow builder no canvas.",
    squad: "automations",
    intents: ["editar fluxo", "automação visual", "abrir fluxos"],
    permissions: ["automations.write"],
    ui: [],
  },
  "automation.open": {
    id: "automation.open",
    name: "Automações",
    description: "Resumo de fluxos reativos e proativos WhatsApp.",
    squad: "automations",
    intents: ["automações", "automacoes", "fluxos whatsapp", "abrir automações"],
    permissions: ["automations.read"],
    ui: ["automation_stats", "nav_suggestions"],
  },
  "automation.create": {
    id: "automation.create",
    name: "Criar automação",
    description: "Gera fluxo a partir de briefing conversacional (ex: pedido completo WhatsApp).",
    squad: "automations",
    intents: [
      "criar automação",
      "criar fluxo",
      "fluxo de pedido",
      "pedido whatsapp",
      "automação whatsapp",
      "comportamento reativo",
    ],
    permissions: ["automations.write"],
    ui: ["automation_flow_preview", "form"],
  },
  "automation.confirm": {
    id: "automation.confirm",
    name: "Confirmar automação",
    description: "Salva ou ativa fluxo gerado no chat.",
    squad: "automations",
    intents: ["ativar fluxo", "salvar automação", "confirmar fluxo"],
    permissions: ["automations.write"],
    ui: ["text"],
  },
  "creative.generate": {
    id: "creative.generate",
    name: "Criativos IA",
    description: "Abre o estúdio de criativos no canvas.",
    squad: "creative",
    intents: ["criar criativo", "gerar imagem", "criativos ia", "criativos"],
    permissions: [],
    ui: [],
  },
  "video.create": {
    id: "video.create",
    name: "Video Studio",
    description: "Abre o estúdio de vídeo no canvas.",
    squad: "creative",
    intents: ["criar vídeo", "video studio", "vídeo"],
    permissions: [],
    ui: [],
  },
  "gallery.open": {
    id: "gallery.open",
    name: "Galeria",
    description: "Abre a galeria de mídia no canvas.",
    squad: "creative",
    intents: ["abrir galeria", "minhas imagens", "galeria"],
    permissions: [],
    ui: ["gallery_stats", "nav_suggestions"],
  },
  "instagram.open": {
    id: "instagram.open",
    name: "Instagram",
    description: "Resumo da conta Instagram Business e studio completo.",
    squad: "social",
    intents: ["instagram", "abrir instagram", "posts instagram", "dm instagram", "reels"],
    permissions: [],
    ui: ["instagram_stats", "nav_suggestions"],
  },
  "instagram.post.create": {
    id: "instagram.post.create",
    name: "Criar post Instagram",
    description: "Gera legenda e imagem com IA a partir de um briefing e mostra preview para publicar ou agendar.",
    squad: "social",
    intents: ["criar post instagram", "postar no insta", "publicar no instagram", "fazer post", "legenda instagram"],
    permissions: [],
    ui: ["instagram_post_preview", "form"],
  },
  "instagram.post.confirm": {
    id: "instagram.post.confirm",
    name: "Confirmar post Instagram",
    description: "Publica, agenda ou salva rascunho após confirmação no chat.",
    squad: "social",
    intents: ["confirmar post", "publicar agora", "agendar post"],
    permissions: [],
    ui: ["text"],
  },
  "instagram.analyze": {
    id: "instagram.analyze",
    name: "Analisar Instagram",
    description: "Métricas, insights e performance da conta.",
    squad: "social",
    intents: ["analisar instagram", "métricas instagram", "performance insta", "insights instagram"],
    permissions: [],
    ui: ["kpi_row", "table"],
  },
  "instagram.messages": {
    id: "instagram.messages",
    name: "DMs Instagram",
    description: "Resumo das conversas no Direct.",
    squad: "social",
    intents: ["dm instagram", "mensagens instagram", "direct instagram"],
    permissions: [],
    ui: ["table", "text"],
  },
  "facebook.open": {
    id: "facebook.open",
    name: "Facebook",
    description: "Resumo da página Facebook e studio completo.",
    squad: "social",
    intents: ["facebook", "abrir facebook", "página facebook", "fb"],
    permissions: [],
    ui: ["facebook_stats", "nav_suggestions"],
  },
  "facebook.post.create": {
    id: "facebook.post.create",
    name: "Criar post Facebook",
    description: "Gera texto e imagem com IA e mostra preview para publicar ou agendar.",
    squad: "social",
    intents: ["criar post facebook", "postar no facebook", "publicar no fb"],
    permissions: [],
    ui: ["facebook_post_preview", "form"],
  },
  "facebook.post.confirm": {
    id: "facebook.post.confirm",
    name: "Confirmar post Facebook",
    description: "Publica, agenda ou salva rascunho após confirmação no chat.",
    squad: "social",
    intents: ["confirmar post facebook", "publicar facebook"],
    permissions: [],
    ui: ["text"],
  },
  "facebook.analyze": {
    id: "facebook.analyze",
    name: "Analisar Facebook",
    description: "Métricas e performance da página.",
    squad: "social",
    intents: ["analisar facebook", "métricas facebook", "insights facebook"],
    permissions: [],
    ui: ["kpi_row", "table"],
  },
  "affiliate.open": {
    id: "affiliate.open",
    name: "Afiliados",
    description: "Resumo do programa de parceiros, comissões e saques.",
    squad: "affiliates",
    intents: ["afiliados", "parceiros", "programa de afiliados", "abrir afiliados"],
    permissions: [],
    ui: ["affiliate_stats", "nav_suggestions"],
  },
  "affiliate.create": {
    id: "affiliate.create",
    name: "Cadastrar afiliado",
    description: "Cria parceiro com link, cupom e acesso à Central do Afiliado.",
    squad: "affiliates",
    intents: ["cadastrar afiliado", "novo parceiro", "criar afiliado"],
    permissions: [],
    ui: ["affiliate_create_preview", "form"],
  },
  "affiliate.create.confirm": {
    id: "affiliate.create.confirm",
    name: "Confirmar cadastro afiliado",
    description: "Confirma criação do parceiro após preview no chat.",
    squad: "affiliates",
    intents: ["confirmar afiliado", "salvar parceiro"],
    permissions: [],
    ui: ["text"],
  },
  "affiliate.config": {
    id: "affiliate.config",
    name: "Configurar programa",
    description: "Ajusta comissão, saque mínimo, cookie e regras do programa.",
    squad: "affiliates",
    intents: ["configurar afiliados", "comissão padrão", "regras do programa"],
    permissions: [],
    ui: ["affiliate_config_preview", "form"],
  },
  "affiliate.config.confirm": {
    id: "affiliate.config.confirm",
    name: "Salvar config afiliados",
    description: "Confirma alterações nas configurações do programa.",
    squad: "affiliates",
    intents: ["salvar configuração afiliados"],
    permissions: [],
    ui: ["text"],
  },
  "affiliate.analyze": {
    id: "affiliate.analyze",
    name: "Analisar afiliados",
    description: "Métricas de cliques, vendas e comissões do programa.",
    squad: "affiliates",
    intents: ["métricas afiliados", "performance parceiros", "analisar afiliados"],
    permissions: [],
    ui: ["affiliate_stats", "kpi_row"],
  },
  "affiliate.approve": {
    id: "affiliate.approve",
    name: "Aprovar afiliados/comissões",
    description: "Lista pendentes de aprovação de parceiros e comissões.",
    squad: "affiliates",
    intents: ["aprovar afiliado", "aprovar comissão", "comissões pendentes"],
    permissions: [],
    ui: ["table", "text"],
  },
  "affiliate.payouts": {
    id: "affiliate.payouts",
    name: "Saques afiliados",
    description: "Gerencia solicitações de saque PIX dos parceiros.",
    squad: "affiliates",
    intents: ["saques afiliados", "pagar afiliado", "pix parceiro"],
    permissions: [],
    ui: ["affiliate_payout_preview", "table"],
  },
  "affiliate.payout.confirm": {
    id: "affiliate.payout.confirm",
    name: "Confirmar saque",
    description: "Marca saque como pago ou em processamento.",
    squad: "affiliates",
    intents: ["confirmar saque", "marcar saque pago"],
    permissions: [],
    ui: ["text"],
  },
  "affiliate.materials": {
    id: "affiliate.materials",
    name: "Materiais afiliados",
    description: "Lista materiais de divulgação para parceiros.",
    squad: "affiliates",
    intents: ["materiais afiliados", "banners parceiros"],
    permissions: [],
    ui: ["table"],
  },
  "agent.configure": {
    id: "agent.configure",
    name: "Configurar agente",
    description: "Abre configuração do agente IA no canvas.",
    squad: "workspace",
    intents: ["configurar agente", "treinar agente", "meu agente", "agente ia"],
    permissions: ["agent.write"],
    ui: [],
  },
};

export const SQUADS: Record<string, SquadDefinition> = {
  workspace: {
    id: "workspace",
    name: "Agente IA",
    description: "Configuração, prontidão e treinamento do agente WhatsApp.",
    skills: ["workspace.overview", "workspace.navigate", "agent.configure"],
  },
  crm: {
    id: "crm",
    name: "CRM",
    description: "Leads, clientes e prospecção.",
    skills: ["lead.prospect", "crm.leads.list", "crm.leads.table", "crm.lead.find", "crm.lead.detail", "crm.leads.search", "crm.clients.table", "crm.clients.list"],
  },
  messages: {
    id: "messages",
    name: "Mensagens",
    description: "Inbox e conversas WhatsApp.",
    skills: ["messages.inbox"],
  },
  campaigns: {
    id: "campaigns",
    name: "Campanhas",
    description: "Criação e gestão de campanhas de mensagens.",
    skills: ["campaigns.list", "campaigns.create"],
  },
  skills: {
    id: "skills",
    name: "Habilidades",
    description: "Brand skills que o agente usa nas conversas.",
    skills: ["skills.list", "skills.train"],
  },
  catalog: {
    id: "catalog",
    name: "Catálogo",
    description: "Produtos, pedidos e estoque da loja.",
    skills: ["catalog.products", "catalog.products.table", "catalog.products.create", "catalog.orders", "order.assisted"],
  },
  dashboard: {
    id: "dashboard",
    name: "Painel",
    description: "Visão geral do negócio.",
    skills: ["dashboard.show", "dashboard.overview"],
  },
  automations: {
    id: "automations",
    name: "Automações",
    description: "Fluxos reativos e proativos WhatsApp — chat ou editor avançado.",
    skills: ["automation.open", "automation.create", "automation.confirm", "flow.builder"],
  },
  creative: {
    id: "creative",
    name: "Criativos",
    description: "Galeria, criativos IA e vídeo.",
    skills: ["creative.generate", "video.create", "gallery.open"],
  },
  social: {
    id: "social",
    name: "Redes sociais",
    description: "Instagram, Facebook e canais sociais.",
    skills: [
      "instagram.open", "instagram.post.create", "instagram.post.confirm", "instagram.analyze", "instagram.messages",
      "facebook.open", "facebook.post.create", "facebook.post.confirm", "facebook.analyze",
    ],
  },
  affiliates: {
    id: "affiliates",
    name: "Afiliados",
    description: "Programa de parceiros — cadastro, comissões, saques e materiais.",
    skills: [
      "affiliate.open", "affiliate.create", "affiliate.create.confirm", "affiliate.config", "affiliate.config.confirm",
      "affiliate.analyze", "affiliate.approve", "affiliate.payouts", "affiliate.payout.confirm", "affiliate.materials",
    ],
  },
  nav: {
    id: "nav",
    name: "Navegação",
    description: "Ajuda e descoberta de funcionalidades.",
    skills: ["nav.help"],
  },
};

export const NAV_PATHS: Record<string, { path: string; label: string }> = {
  dashboard: { path: "/admin", label: "Painel" },
  leads: { path: "/leads", label: "Leads" },
  clientes: { path: "/clientes", label: "Clientes" },
  busca: { path: "/busca", label: "Busca" },
  mensagens: { path: "/mensagens", label: "Mensagens" },
  campanhas: { path: "/campanhas", label: "Campanhas" },
  agente: { path: "/agente", label: "Agente IA" },
  habilidades: { path: "/habilidades", label: "Habilidades" },
  produtos: { path: "/produtos", label: "Produtos" },
  pedidos: { path: "/pedidos", label: "Pedidos" },
  estoque: { path: "/estoque", label: "Estoque" },
  criativos: { path: "/criativos", label: "Criativos IA" },
  galeria: { path: "/galeria", label: "Galeria" },
  instagram: { path: "/instagram", label: "Instagram" },
  facebook: { path: "/facebook", label: "Facebook" },
  whatsapp: { path: "/configuracoes?tab=whatsapp", label: "WhatsApp" },
  automacoes: { path: "/automacoes", label: "Automações" },
  afiliados: { path: "/afiliados", label: "Afiliados" },
  configuracoes: { path: "/configuracoes", label: "Configurações" },
};

export function buildSkillsCatalog(): string {
  return Object.values(SQUADS)
    .map((squad) => {
      const skillLines = squad.skills
        .map((id) => {
          const sk = SKILLS[id];
          if (!sk) return "";
          return `    - ${sk.id}: ${sk.name} — ${sk.description} (intents: ${sk.intents.slice(0, 4).join(", ")})`;
        })
        .filter(Boolean)
        .join("\n");
      return `  [${squad.id}] ${squad.name}: ${squad.description}\n${skillLines}`;
    })
    .join("\n\n");
}