import type { SkillDefinition, SquadDefinition } from "./types";

export const SKILLS: Record<string, SkillDefinition> = {
  "workspace.overview": {
    id: "workspace.overview",
    name: "Ver prontidão do agente",
    description: "Mostra score de prontidão e checklist do agente WhatsApp.",
    squad: "workspace",
    intents: ["como está meu agente", "prontidão", "readiness", "status do agente", "agente configurado"],
    permissions: ["agent.read"],
    ui: ["readiness_card", "checklist"],
  },
  "workspace.navigate": {
    id: "workspace.navigate",
    name: "Configurar agente",
    description: "Navega para a página de configuração do agente IA.",
    squad: "workspace",
    intents: ["configurar agente", "treinar agente", "editar agente", "perfil do agente"],
    permissions: ["agent.write"],
    ui: ["nav_suggestions"],
  },
  "crm.leads.list": {
    id: "crm.leads.list",
    name: "Listar leads",
    description: "Mostra resumo de leads e navega para a lista.",
    squad: "crm",
    intents: ["meus leads", "listar leads", "ver leads", "quantos leads"],
    permissions: ["leads.read"],
    ui: ["kpi_row", "nav_suggestions"],
  },
  "crm.leads.search": {
    id: "crm.leads.search",
    name: "Buscar leads",
    description: "Alias para busca no mapa (modo paleteiro).",
    squad: "crm",
    intents: ["buscar leads no mapa"],
    permissions: ["leads.read"],
    ui: ["form", "prospect_stats"],
  },
  "lead.prospect": {
    id: "lead.prospect",
    name: "Prospectar no mapa",
    description: "Busca Google Maps com modo paleteiro — arrastar, capturar, radar.",
    squad: "crm",
    intents: ["prospectar", "buscar no mapa", "paleteiro", "panfleteiro", "google maps", "encontrar empresas", "prospectar leads"],
    permissions: ["leads.read", "leads.write"],
    ui: ["form", "prospect_stats"],
  },
  "crm.leads.table": {
    id: "crm.leads.table",
    name: "Tabela de leads recentes",
    description: "Mostra tabela com os leads mais recentes.",
    squad: "crm",
    intents: ["tabela de leads", "últimos leads", "leads recentes"],
    permissions: ["leads.read"],
    ui: ["table", "kpi_row"],
  },
  "crm.lead.find": {
    id: "crm.lead.find",
    name: "Buscar lead por nome",
    description: "Formulário de busca e tabela de resultados.",
    squad: "crm",
    intents: ["encontrar lead", "lead chamado", "procurar lead", "editar lead"],
    permissions: ["leads.read"],
    ui: ["form", "table"],
  },
  "crm.clients.table": {
    id: "crm.clients.table",
    name: "Ver clientes",
    description: "Lista clientes convertidos e relacionamento ativo.",
    squad: "crm",
    intents: ["clientes", "ver clientes", "meus clientes", "base de clientes"],
    permissions: ["clients.read"],
    ui: ["clients_stats", "kpi_row", "table"],
  },
  "crm.clients.list": {
    id: "crm.clients.list",
    name: "Lista de clientes",
    description: "Tabela de clientes com filtros.",
    squad: "crm",
    intents: ["lista de clientes", "tabela clientes"],
    permissions: ["clients.read"],
    ui: ["clients_stats", "table"],
  },
  "crm.lead.detail": {
    id: "crm.lead.detail",
    name: "Detalhe do lead",
    description: "Card com dados do lead selecionado.",
    squad: "crm",
    intents: [],
    permissions: ["leads.read"],
    ui: ["lead_card", "button"],
  },
  "messages.inbox": {
    id: "messages.inbox",
    name: "Conversas recentes",
    description: "Tabela com últimas conversas WhatsApp.",
    squad: "messages",
    intents: ["mensagens", "conversas", "inbox", "whatsapp conversas", "atendimento"],
    permissions: ["messages.read"],
    ui: ["table", "kpi_row"],
  },
  "catalog.products.table": {
    id: "catalog.products.table",
    name: "Tabela de produtos",
    description: "Lista produtos com estoque.",
    squad: "catalog",
    intents: ["lista de produtos", "tabela produtos", "ver estoque detalhado"],
    permissions: ["catalog.read"],
    ui: ["products_stats", "table"],
  },
  "campaigns.list": {
    id: "campaigns.list",
    name: "Ver campanhas",
    description: "Mostra campanhas ativas e totais.",
    squad: "campaigns",
    intents: ["campanhas", "minhas campanhas", "campanhas ativas"],
    permissions: ["campaigns.read"],
    ui: ["campaigns_stats", "kpi_row", "nav_suggestions"],
  },
  "campaigns.create": {
    id: "campaigns.create",
    name: "Criar campanha com IA",
    description: "Abre o wizard de criação de campanha via squad de IA.",
    squad: "campaigns",
    intents: ["criar campanha", "nova campanha", "campanha com ia", "disparar mensagens"],
    permissions: ["campaigns.write"],
    ui: ["confirmation"],
  },
  "skills.list": {
    id: "skills.list",
    name: "Ver habilidades",
    description: "Lista habilidades (brand skills) do agente.",
    squad: "skills",
    intents: ["habilidades", "skills", "o que o agente sabe"],
    permissions: ["skills.read"],
    ui: ["skill_list", "nav_suggestions"],
  },
  "skills.train": {
    id: "skills.train",
    name: "Ensinar nova habilidade",
    description: "Abre o wizard de treinamento de habilidade.",
    squad: "skills",
    intents: ["ensinar agente", "nova habilidade", "treinar skill", "criar habilidade"],
    permissions: ["skills.write"],
    ui: ["confirmation"],
  },
  "catalog.products": {
    id: "catalog.products",
    name: "Ver produtos",
    description: "Mostra resumo do catálogo e estoque.",
    squad: "catalog",
    intents: ["produtos", "catálogo", "estoque", "inventário"],
    permissions: ["catalog.read"],
    ui: ["products_stats", "kpi_row", "nav_suggestions"],
  },
  "catalog.products.create": {
    id: "catalog.products.create",
    name: "Criar produto",
    description: "Fluxo conversacional para cadastrar produto com IA.",
    squad: "catalog",
    intents: ["criar produto", "novo produto", "cadastrar produto", "adicionar produto", "lançar produto"],
    permissions: ["catalog.write"],
    ui: ["form", "confirmation", "text"],
  },
  "catalog.orders": {
    id: "catalog.orders",
    name: "Ver pedidos",
    description: "Mostra resumo de pedidos da loja.",
    squad: "catalog",
    intents: ["pedidos", "vendas", "ordens"],
    permissions: ["catalog.read"],
    ui: ["orders_stats", "kpi_row", "table"],
  },
  "nav.help": {
    id: "nav.help",
    name: "Ajuda e navegação",
    description: "Sugere rotas e ações disponíveis no painel.",
    squad: "nav",
    intents: ["ajuda", "o que posso fazer", "menu", "navegar", "ir para"],
    permissions: [],
    ui: ["nav_suggestions"],
  },
  "dashboard.overview": {
    id: "dashboard.overview",
    name: "Visão geral",
    description: "KPIs principais do negócio (inline).",
    squad: "dashboard",
    intents: ["resumo rápido", "kpis", "números do negócio"],
    permissions: [],
    ui: ["kpi_row", "nav_suggestions"],
  },
  "dashboard.show": {
    id: "dashboard.show",
    name: "Painel completo",
    description: "Abre o dashboard no canvas lateral.",
    squad: "dashboard",
    intents: ["painel", "dashboard", "visão geral", "como está o negócio", "mostrar painel"],
    permissions: [],
    ui: [],
  },
  "order.assisted": {
    id: "order.assisted",
    name: "Pedido assistido",
    description: "Fluxo conversacional para montar um pedido.",
    squad: "catalog",
    intents: ["fazer pedido", "tirar pedido", "pedido para", "preciso fazer um pedido"],
    permissions: ["catalog.write"],
    ui: ["form", "table", "confirmation"],
  },
  "flow.builder": {
    id: "flow.builder",
    name: "Editor de fluxos",
    description: "Abre o flow builder no canvas.",
    squad: "automations",
    intents: ["editar fluxo", "criar fluxo", "automação visual", "fluxos"],
    permissions: ["automations.write"],
    ui: [],
  },
  "creative.generate": {
    id: "creative.generate",
    name: "Criativos IA",
    description: "Abre o estúdio de criativos no canvas.",
    squad: "creative",
    intents: ["criar criativo", "gerar imagem", "criativos ia", "criativos"],
    permissions: [],
    ui: [],
  },
  "video.create": {
    id: "video.create",
    name: "Video Studio",
    description: "Abre o estúdio de vídeo no canvas.",
    squad: "creative",
    intents: ["criar vídeo", "video studio", "vídeo"],
    permissions: [],
    ui: [],
  },
  "gallery.open": {
    id: "gallery.open",
    name: "Galeria",
    description: "Abre a galeria de mídia no canvas.",
    squad: "creative",
    intents: ["abrir galeria", "minhas imagens", "galeria"],
    permissions: [],
    ui: ["gallery_stats", "nav_suggestions"],
  },
  "agent.configure": {
    id: "agent.configure",
    name: "Configurar agente",
    description: "Abre configuração do agente IA no canvas.",
    squad: "workspace",
    intents: ["configurar agente", "treinar agente", "meu agente", "agente ia"],
    permissions: ["agent.write"],
    ui: [],
  },
};

export const SQUADS: Record<string, SquadDefinition> = {
  workspace: {
    id: "workspace",
    name: "Agente IA",
    description: "Configuração, prontidão e treinamento do agente WhatsApp.",
    skills: ["workspace.overview", "workspace.navigate", "agent.configure"],
  },
  crm: {
    id: "crm",
    name: "CRM",
    description: "Leads, clientes e prospecção.",
    skills: ["lead.prospect", "crm.leads.list", "crm.leads.table", "crm.lead.find", "crm.lead.detail", "crm.leads.search", "crm.clients.table", "crm.clients.list"],
  },
  messages: {
    id: "messages",
    name: "Mensagens",
    description: "Inbox e conversas WhatsApp.",
    skills: ["messages.inbox"],
  },
  campaigns: {
    id: "campaigns",
    name: "Campanhas",
    description: "Criação e gestão de campanhas de mensagens.",
    skills: ["campaigns.list", "campaigns.create"],
  },
  skills: {
    id: "skills",
    name: "Habilidades",
    description: "Brand skills que o agente usa nas conversas.",
    skills: ["skills.list", "skills.train"],
  },
  catalog: {
    id: "catalog",
    name: "Catálogo",
    description: "Produtos, pedidos e estoque da loja.",
    skills: ["catalog.products", "catalog.products.table", "catalog.products.create", "catalog.orders", "order.assisted"],
  },
  dashboard: {
    id: "dashboard",
    name: "Painel",
    description: "Visão geral do negócio.",
    skills: ["dashboard.show", "dashboard.overview"],
  },
  automations: {
    id: "automations",
    name: "Automações",
    description: "Fluxos e automações visuais.",
    skills: ["flow.builder"],
  },
  creative: {
    id: "creative",
    name: "Criativos",
    description: "Galeria, criativos IA e vídeo.",
    skills: ["creative.generate", "video.create", "gallery.open"],
  },
  nav: {
    id: "nav",
    name: "Navegação",
    description: "Ajuda e descoberta de funcionalidades.",
    skills: ["nav.help"],
  },
};

export const NAV_PATHS: Record<string, { path: string; label: string }> = {
  dashboard: { path: "/admin", label: "Painel" },
  leads: { path: "/leads", label: "Leads" },
  clientes: { path: "/clientes", label: "Clientes" },
  busca: { path: "/busca", label: "Busca" },
  mensagens: { path: "/mensagens", label: "Mensagens" },
  campanhas: { path: "/campanhas", label: "Campanhas" },
  agente: { path: "/agente", label: "Agente IA" },
  habilidades: { path: "/habilidades", label: "Habilidades" },
  produtos: { path: "/produtos", label: "Produtos" },
  pedidos: { path: "/pedidos", label: "Pedidos" },
  estoque: { path: "/estoque", label: "Estoque" },
  criativos: { path: "/criativos", label: "Criativos IA" },
  galeria: { path: "/galeria", label: "Galeria" },
  whatsapp: { path: "/configuracoes?tab=whatsapp", label: "WhatsApp" },
  automacoes: { path: "/automacoes", label: "Automações" },
  configuracoes: { path: "/configuracoes", label: "Configurações" },
};

export function buildSkillsCatalog(): string {
  return Object.values(SQUADS)
    .map((squad) => {
      const skillLines = squad.skills
        .map((id) => {
          const sk = SKILLS[id];
          if (!sk) return "";
          return `    - ${sk.id}: ${sk.name} — ${sk.description} (intents: ${sk.intents.slice(0, 4).join(", ")})`;
        })
        .filter(Boolean)
        .join("\n");
      return `  [${squad.id}] ${squad.name}: ${squad.description}\n${skillLines}`;
    })
    .join("\n\n");
}