require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');

function quoteIdent(name) {
  return '"' + String(name).replace(/"/g, '""') + '"';
}

function normalizeDefault(value) {
  if (value === null || value === undefined) return null;
  let text = String(value).trim();
  if (!text || text.toUpperCase() === 'NULL') return null;
  if (text.startsWith("'") && text.endsWith("'") && text.length >= 2) {
    text = text.slice(1, -1);
  }
  if (/^current_timestamp(?:\(\))?$/i.test(text)) return 'now()';
  return text;
}

function mapColumnType(col) {
  const dataType = String(col.data_type || '').toLowerCase();
  const columnType = String(col.column_type || '').toLowerCase();
  const extra = String(col.extra || '').toLowerCase();

  let pgType = 'text';

  if (dataType === 'tinyint') {
    if (/tinyint\(1\)/.test(columnType)) pgType = 'boolean';
    else pgType = 'smallint';
  } else if (dataType === 'smallint') pgType = 'smallint';
  else if (dataType === 'mediumint' || dataType === 'int' || dataType === 'integer') pgType = 'integer';
  else if (dataType === 'bigint') pgType = 'bigint';
  else if (dataType === 'decimal' || dataType === 'numeric') {
    const m = columnType.match(/\((\d+),(\d+)\)/);
    pgType = m ? `numeric(${m[1]},${m[2]})` : 'numeric';
  } else if (dataType === 'float' || dataType === 'double' || dataType === 'double precision') pgType = 'double precision';
  else if (dataType === 'char') {
    const m = columnType.match(/\((\d+)\)/);
    pgType = m ? `char(${m[1]})` : 'char';
  } else if (dataType === 'varchar') {
    const m = columnType.match(/\((\d+)\)/);
    pgType = m ? `varchar(${m[1]})` : 'text';
  } else if (['text', 'tinytext', 'mediumtext', 'longtext'].includes(dataType)) pgType = 'text';
  else if (dataType === 'json') pgType = 'jsonb';
  else if (dataType === 'date') pgType = 'date';
  else if (dataType === 'time') pgType = 'time';
  else if (dataType === 'datetime' || dataType === 'timestamp') pgType = 'timestamp';
  else if (dataType === 'enum' || dataType === 'set') pgType = 'text';
  else if (['blob', 'tinyblob', 'mediumblob', 'longblob', 'binary', 'varbinary'].includes(dataType)) pgType = 'bytea';

  return {
    pgType,
    isAutoIncrement: extra.includes('auto_increment'),
  };
}

function pgLiteral(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (value instanceof Date) return `'${value.toISOString().replace('T', ' ').replace('Z', '')}'`;

  const text = String(value);
  const escaped = text.replace(/'/g, "''");
  return `'${escaped}'`;
}

async function main() {
  const db = process.env.MYSQL_DATABASE;
  const schemaPath = path.join(process.cwd(), 'data', 'mysql_schema_export.json');
  const payload = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));

  const conn = await mysql.createConnection({
    host: process.env.MYSQL_HOST,
    port: Number(process.env.MYSQL_PORT || 3306),
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    database: db,
  });

  const ddl = [];
  const fkStatements = [];
  const indexes = [];
  const dataInserts = [];
  const dataSummary = [];

  ddl.push('-- Generated from MySQL schema');
  ddl.push('CREATE EXTENSION IF NOT EXISTS pgcrypto;');

  for (const table of payload.tables) {
    const tableName = table.tableName;
    const cols = [];

    for (const col of table.columns) {
      const { pgType, isAutoIncrement } = mapColumnType(col);
      let line = `${quoteIdent(col.column_name)} ${pgType}`;

      if (isAutoIncrement && ['integer', 'bigint', 'smallint'].includes(pgType)) {
        line += ' GENERATED BY DEFAULT AS IDENTITY';
      }

      if (String(col.is_nullable).toUpperCase() !== 'YES') {
        line += ' NOT NULL';
      }

      const defaultValue = normalizeDefault(col.column_default);
      if (defaultValue !== null && !isAutoIncrement) {
        if (defaultValue === 'now()') {
          line += ' DEFAULT now()';
        } else if (pgType === 'boolean') {
          if (String(defaultValue).toLowerCase() === '1' || String(defaultValue).toLowerCase() === 'true') line += ' DEFAULT TRUE';
          else if (String(defaultValue).toLowerCase() === '0' || String(defaultValue).toLowerCase() === 'false') line += ' DEFAULT FALSE';
        } else if (['integer', 'bigint', 'smallint', 'numeric', 'double precision'].some((t) => pgType.startsWith(t))) {
          if (!Number.isNaN(Number(defaultValue))) line += ` DEFAULT ${defaultValue}`;
        } else if (pgType === 'jsonb') {
          const escaped = String(defaultValue).replace(/'/g, "''");
          line += ` DEFAULT '${escaped}'::jsonb`;
        } else {
          const escaped = String(defaultValue).replace(/'/g, "''");
          line += ` DEFAULT '${escaped}'`;
        }
      }

      cols.push(line);
    }

    if (Array.isArray(table.primaryKey) && table.primaryKey.length > 0) {
      const pkCols = table.primaryKey.map((pk) => quoteIdent(pk.column_name)).join(', ');
      cols.push(`PRIMARY KEY (${pkCols})`);
    }

    ddl.push(`CREATE TABLE IF NOT EXISTS ${quoteIdent(tableName)} (`);
    ddl.push('  ' + cols.join(',\n  '));
    ddl.push(');');

    const indexMap = new Map();
    for (const idx of table.indexes || []) {
      const key = idx.index_name;
      if (!indexMap.has(key)) indexMap.set(key, []);
      indexMap.get(key).push(idx);
    }

    for (const [indexName, parts] of indexMap.entries()) {
      const sorted = parts.sort((a, b) => Number(a.seq_in_index) - Number(b.seq_in_index));
      const colsSql = sorted.map((p) => quoteIdent(p.column_name)).join(', ');
      const unique = Number(sorted[0].non_unique) === 0 ? 'UNIQUE ' : '';
      const safeName = `${tableName}_${indexName}`.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      indexes.push(`CREATE ${unique}INDEX IF NOT EXISTS ${quoteIdent(safeName)} ON ${quoteIdent(tableName)} (${colsSql});`);
    }

    const fkMap = new Map();
    for (const fk of table.foreignKeys || []) {
      if (!fkMap.has(fk.constraint_name)) fkMap.set(fk.constraint_name, []);
      fkMap.get(fk.constraint_name).push(fk);
    }

    for (const [constraintName, parts] of fkMap.entries()) {
      const sorted = parts.sort((a, b) => Number(a.ordinal_position) - Number(b.ordinal_position));
      const localCols = sorted.map((p) => quoteIdent(p.column_name)).join(', ');
      const refTable = sorted[0].referenced_table_name;
      const refCols = sorted.map((p) => quoteIdent(p.referenced_column_name)).join(', ');
      const onDelete = String(sorted[0].delete_rule || '').toUpperCase();
      const onUpdate = String(sorted[0].update_rule || '').toUpperCase();
      const safeConstraint = `${tableName}_${constraintName}`.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      const tailDelete = onDelete && onDelete !== 'NO ACTION' ? ` ON DELETE ${onDelete}` : '';
      const tailUpdate = onUpdate && onUpdate !== 'NO ACTION' ? ` ON UPDATE ${onUpdate}` : '';
      fkStatements.push(
        `ALTER TABLE ${quoteIdent(tableName)} ADD CONSTRAINT ${quoteIdent(safeConstraint)} FOREIGN KEY (${localCols}) REFERENCES ${quoteIdent(refTable)} (${refCols})${tailDelete}${tailUpdate};`
      );
    }

    if (Number(table.rowCount || 0) > 0) {
      const [rows] = await conn.query(`SELECT * FROM ${quoteIdent(tableName).replace(/"/g, '`')}`);
      if (rows.length > 0) {
        const colNames = Object.keys(rows[0]);
        const colsSql = colNames.map((c) => quoteIdent(c)).join(', ');
        for (const row of rows) {
          const valuesSql = colNames.map((c) => pgLiteral(row[c])).join(', ');
          dataInserts.push(`INSERT INTO ${quoteIdent(tableName)} (${colsSql}) VALUES (${valuesSql});`);
        }
      }
      dataSummary.push({ table: tableName, rows: Number(table.rowCount || 0) });
    }
  }

  ddl.push(...indexes);
  ddl.push(...fkStatements);

  const schemaOut = path.join(process.cwd(), 'data', 'pg_schema.sql');
  const dataOut = path.join(process.cwd(), 'data', 'pg_data.sql');
  const summaryOut = path.join(process.cwd(), 'data', 'pg_data_summary.json');

  fs.writeFileSync(schemaOut, ddl.join('\n') + '\n', 'utf8');
  fs.writeFileSync(dataOut, dataInserts.join('\n') + '\n', 'utf8');
  fs.writeFileSync(summaryOut, JSON.stringify({ database: db, dataSummary }, null, 2), 'utf8');

  console.log('PG_SCHEMA', schemaOut);
  console.log('PG_DATA', dataOut, 'ROWS', dataInserts.length);
  console.log('PG_SUMMARY', summaryOut);

  await conn.end();
}

main().catch((err) => {
  console.error('MYSQL_TO_POSTGRES_EXPORT_ERROR', err.message);
  process.exit(1);
});
