import { ArrowDownRight, ArrowUpRight, Pencil, Trash2 } from 'lucide-react'
import { money } from '@/lib/admin/helpers'

type Tx = {id:string;kind:'income'|'expense';description:string;category:string;category_id?:string;amount:number;occurred_on:string;status:'paid'|'pending';payment_method?:string;document_number?:string;notes?:string;source_type?:string;source_label?:string}
const dateText=(value:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',timeZone:'UTC'}).format(new Date(`${value.slice(0,10)}T12:00:00Z`))

export function TransactionRows({rows,edit,remove}:{rows:Tx[];edit:(v:Tx)=>void;remove:(v:Tx)=>void}) {
  if(!rows.length)return <div className="min-h-52 px-6 py-10 flex flex-col items-center justify-center text-center"><div className="size-12 rounded-[18px] bg-gray-100 grid place-items-center text-gray-400"><ArrowDownRight size={20}/></div><p className="text-[13px] font-semibold text-gray-700 mt-3">Nenhuma movimentação neste período</p><p className="text-[11px] text-gray-400 mt-1">Altere as datas ou registre o primeiro lançamento.</p></div>
  return <><div className="sm:hidden divide-y divide-gray-100">{rows.map(r=>{const Icon=r.kind==='income'?ArrowUpRight:ArrowDownRight;return <button key={r.id} onClick={()=>edit(r)} className="w-full p-4 text-left active:bg-gray-50"><div className="flex items-center gap-3"><div className={`size-10 rounded-[14px] grid place-items-center shrink-0 ${r.kind==='income'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}><Icon size={17}/></div><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-3"><p className="text-[12px] font-semibold truncate">{r.description}</p><p className={`text-[13px] font-bold tabular-nums shrink-0 ${r.kind==='income'?'text-emerald-700':'text-gray-900'}`}>{r.kind==='income'?'+':'−'} {money(r.amount)}</p></div><div className="flex items-center justify-between gap-3 mt-1"><p className="text-[10px] text-gray-400 truncate">{r.category} · {dateText(r.occurred_on)}</p><span className={`text-[9px] font-bold ${r.status==='paid'?'text-emerald-600':'text-amber-600'}`}>{r.status==='paid'?'REALIZADO':'PENDENTE'}</span></div></div></div></button>})}</div><table className="hidden sm:table w-full min-w-[760px]"><thead><tr className="bg-gray-50 text-[10px] uppercase tracking-wider text-gray-400">{['Data','Descrição','Categoria','Status','Valor','Ações'].map(x=><th key={x} className="text-left px-4 py-3">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-gray-100 text-[12px]"><td className="px-4 py-3 text-gray-500">{dateText(r.occurred_on)}</td><td className="px-4 py-3"><p className="font-semibold">{r.description}</p><p className="text-[10px] text-gray-400">{r.document_number||r.payment_method||'Sem documento'}</p></td><td className="px-4 py-3 text-gray-600">{r.category}</td><td className="px-4 py-3"><span className={`px-2 py-1 rounded-full text-[10px] font-semibold ${r.status==='paid'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{r.status==='paid'?'Realizado':'Pendente'}</span></td><td className={`px-4 py-3 font-bold tabular-nums ${r.kind==='income'?'text-emerald-700':'text-rose-700'}`}>{r.kind==='income'?'+':'−'} {money(r.amount)}</td><td className="px-4 py-3"><button aria-label="Editar" onClick={()=>edit(r)} className="p-2"><Pencil size={14}/></button><button aria-label="Excluir" onClick={()=>remove(r)} className="p-2 text-rose-600"><Trash2 size={14}/></button></td></tr>)}</tbody></table></>
}
